"""Not needed we can remove this."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_core.ipynb.

# %% auto 0
__all__ = ['hello']

# %% ../nbs/00_core.ipynb 3
def hello(name):
    return f"Hello {name}!"
